#! /bin/bash
mount -t proc none /proc
mount -t sysfs none /sys
#mount -t debugfs none /sys/kernel/debug/

#echo deleting then creating mytmpfs
rm -rf mytmpfs
mkdir /mytmpfs
mount -t tmpfs -o size=4g tmpfs /mytmpfs

#echo Pinning virt queues to cores
#./set_irq_affinity_virtio.sh

#/sbin/ip addr add 10.0.2.15 dev eth0
#/sbin/ip link set dev eth0 up

exec /bin/bash

