#! /bin/bash
mount -t proc none /proc
mount -t sysfs none /sys
echo "Creating tmpfs"
mkdir -p /mytmpfs
mount -t tmpfs -o size=4g tmpfs /mytmpfs
echo "Done"
echo "df -h /mytmpfs"
df -h /mytmpfs
#kexec -p bzImage --initrd=final-initrd.cpio.gz --append="root=/dev/ram0 rw irqpoll nosmp maxcpus=0 reset_devices console=ttyS0,115200 ip=192.168.19.8:::255.255.255.0::eth0:none appMac='90:e2:ba:ad:96:d4' appIp='192.168.19.8/24' appNode='neu-15-8' appCtlServer='192.168.1.2' appCtlUser='root' appCtlDir='' appCtlFile='neu-15-8.pipe' appEnd='sshd'"
exec /bin/bash
